# Generated by Django 6.0.3 on 2026-04-07 13:05

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('local', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('inicio_ev', models.TimeField(default=datetime.time(8, 0))),
                ('termino_ev', models.TimeField(default=datetime.time(18, 0))),
            ],
        ),
        migrations.CreateModel(
            name='Interesse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('PAIS', 'País'), ('PRECO', 'Faixa de Preço'), ('TIPO', 'Tipo de Produto'), ('MARCA', 'Marca de Produto'), ('ROTULOS', 'Rotulo de Produto'), ('PERFIL', 'Perfil Desejado'), ('VOLUME', 'Volume de Produção/Aquisição'), ('REGIAO', 'Região do Brasil'), ('IDIOMA', 'Idioma de origem'), ('OUTRO', 'Outro')], default='OUTRO', max_length=20)),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'unique_together': {('categoria', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('site', models.CharField(blank=True, max_length=255)),
                ('segmento', models.CharField(blank=True, max_length=255)),
                ('modalidade', models.CharField(blank=True, choices=[('COMPRADOR', 'Comprador'), ('EXPOSITOR', 'Expositor')], default='EXPOSITOR', max_length=255)),
                ('interesses', models.ManyToManyField(blank=True, related_name='empresas', to='core.interesse')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilComprador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rotulos_internacionais', models.IntegerField(blank=True, null=True)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
                ('paises_que_trabalha', models.ManyToManyField(blank=True, related_name='compradores_paises', to='core.interesse')),
                ('preco_medio', models.ManyToManyField(blank=True, related_name='compradores_preco', to='core.interesse')),
                ('regioes_interesse', models.ManyToManyField(blank=True, related_name='compradores_regioes', to='core.interesse')),
                ('tipos_produto', models.ManyToManyField(blank=True, related_name='compradores_tipos', to='core.interesse')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilExpositor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
                ('pais_origem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expositores_pais', to='core.interesse')),
                ('perfil_comprador_desejado', models.ManyToManyField(blank=True, related_name='expositores_perfil', to='core.interesse')),
                ('preco_faixa', models.ManyToManyField(blank=True, related_name='expositores_preco', to='core.interesse')),
                ('regioes_brasil', models.ManyToManyField(blank=True, related_name='expositores_regioes', to='core.interesse')),
                ('tipos_produto', models.ManyToManyField(blank=True, related_name='expositores_tipos', to='core.interesse')),
            ],
        ),
        migrations.CreateModel(
            name='Representante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representantes', to='core.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Rodada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('duracao', models.IntegerField(choices=[(15, '15 minutos'), (20, '20 minutos'), (30, '30 minutos')], default=20)),
                ('inicio_ro', models.TimeField(default=django.utils.timezone.now)),
                ('fim_ro', models.TimeField(default=django.utils.timezone.now)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rodadas', to='core.evento')),
            ],
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('comprador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mesas_como_comprador', to='core.empresa')),
                ('expositor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mesas_como_expositor', to='core.empresa')),
                ('rodada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.rodada')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.TimeField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='core.mesa')),
            ],
            options={
                'unique_together': {('mesa', 'empresa')},
            },
        ),
    ]
