# Generated by Django 6.0.3 on 2026-04-07 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=100, unique=True)),
                ("descricao", models.TextField(blank=True, null=True)),
                ("ordem", models.PositiveIntegerField(default=0)),
            ],
        ),

        migrations.AddField(
            model_name="interesse",
            name="categoria_fk",
            field=models.ForeignKey(
                to="core.Categoria",
                on_delete=models.CASCADE,
                null=True,
                blank=True,
                related_name="interesses"
            ),
        ),
    ]

'''
    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.AlterField(
            model_name='mesa',
            name='rodada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mesas', to='core.rodada'),
        ),
        migrations.AlterField(
            model_name='interesse',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.categoria'),
        ),
    ]
'''
