# Generated by Django 6.0.5 on 2026-06-12 23:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_configuracao'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenResetSenha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('valido_ate', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='ConfiguracaoSistema',
        ),
        migrations.AddField(
            model_name='configuracao',
            name='email_recuperacao',
            field=models.EmailField(default='eloibgq@gmail.com', max_length=254),
        ),
        migrations.DeleteModel(
            name='SolicitacaoAcesso',
        ),
    ]
