# Generated by Django 6.0.3 on 2026-04-07 17:17
# 0003_migrar_categorias.py
from django.db import migrations

def migrar_categorias(apps, schema_editor):
    Categoria = apps.get_model("core", "Categoria")
    Interesse = apps.get_model("core", "Interesse")

    categorias_map = {
        "PAIS": "País",
        "PRECO": "Faixa de Preço",
        "TIPO": "Tipo de Produto",
        "MARCA": "Marca de Produto",
        "ROTULOS": "Rótulo de Produto",
        "PERFIL": "Perfil Desejado",
        "VOLUME": "Volume de Produção/Aquisição",
        "REGIAO": "Região do Brasil",
        "IDIOMA": "Idioma de origem",
        "OUTRO": "Outro",
    }

    # Criar categorias
    created = {}
    for key, nome in categorias_map.items():
        created[key] = Categoria.objects.create(nome=nome)

    # Migrar interesses antigos
    for interesse in Interesse.objects.all():
        categoria_key = interesse.categoria  # valor antigo (string)
        interesse.categoria_fk = created.get(categoria_key)
        interesse.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_categoria_alter_mesa_rodada_and_more'),
    ]

    operations = [
        migrations.RunPython(migrar_categorias),
    ]
