# Generated by Django 6.0.5 on 2026-06-12 23:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tokenresetsenha_delete_configuracaosistema_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracao',
            name='identificador_usuario',
            field=models.CharField(default='admin001', max_length=50, validators=[django.core.validators.MinLengthValidator(7), django.core.validators.RegexValidator(message='O identificador deve ser alfanumérico (sem espaços) e ter pelo menos 7 caracteres.', regex='^[a-zA-Z0-9]+$')]),
        ),
    ]
