# Generated by Django 6.0.5 on 2026-06-13 01:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_configuracao_identificador_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracao',
            name='identificador_usuario',
            field=models.CharField(default='eloibgq', max_length=50, validators=[django.core.validators.MinLengthValidator(7), django.core.validators.RegexValidator(message='O identificador deve ser alfanumérico (sem espaços) e ter pelo menos 7 caracteres.', regex='^[a-zA-Z0-9]+$')]),
        ),
    ]
