# Generated by Django 6.0.5 on 2026-06-13 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_configuracao_identificador_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracao',
            name='senha_rodanegocios',
        ),
    ]
