# Generated by Django 6.0.3 on 2026-04-08 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_categoria_options_alter_categoria_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilexpositor',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='perfilexpositor',
            name='pais_origem',
        ),
        migrations.RemoveField(
            model_name='perfilexpositor',
            name='perfil_comprador_desejado',
        ),
        migrations.RemoveField(
            model_name='perfilexpositor',
            name='preco_faixa',
        ),
        migrations.RemoveField(
            model_name='perfilexpositor',
            name='regioes_brasil',
        ),
        migrations.RemoveField(
            model_name='perfilexpositor',
            name='tipos_produto',
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nome', 'ordem']},
        ),
        migrations.DeleteModel(
            name='PerfilComprador',
        ),
        migrations.DeleteModel(
            name='PerfilExpositor',
        ),
    ]
