# Generated by Django 6.0.5 on 2026-06-13 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_configuracao_senha_rodanegocios'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracao',
            options={'permissions': [('pode_acessar_rodanegocios', 'Pode acessar o Rodanegócios')]},
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='identificador_usuario',
            field=models.CharField(max_length=50),
        ),
    ]
