# Generated by Django 6.0.3 on 2026-04-09 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_perfilexpositor_empresa_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reserva',
        ),
    ]
