# Generated by Django 6.0.3 on 2026-04-10 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_delete_reserva'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participa', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.evento')),
            ],
            options={
                'unique_together': {('empresa', 'evento')},
            },
        ),
        migrations.AddField(
            model_name='evento',
            name='participantes',
            field=models.ManyToManyField(related_name='eventos_participantes', through='core.EmpresaEvento', to='core.empresa'),
        ),
    ]
