# Generated by Django 6.0.3 on 2026-04-10 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_empresaevento_evento_participantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='representante',
            name='cargo',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
