# Generated by Django 6.0.3 on 2026-04-10 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_representante_cargo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesa',
            name='expositor',
        ),
        migrations.AddField(
            model_name='mesa',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mesas_como_vendedor', to='core.empresa'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='modalidade',
            field=models.CharField(blank=True, choices=[('COMPRADOR', 'Comprador'), ('VENDEDOR', 'Vendedor')], default='VENDEDOR', max_length=255),
        ),
    ]
