# Generated by Django 6.0.3 on 2026-04-13 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_empresa_endereco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='estado',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='rua',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
