# Generated by Django 6.0.3 on 2026-04-13 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_endereco_estado_alter_endereco_rua'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representante',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
