# Generated by Django 6.0.3 on 2026-04-22 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_configuracaosistema'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelacionamentoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_relacao', models.CharField(choices=[('CLIENTE', 'Cliente'), ('FORNECEDOR', 'Fornecedor'), ('PARCEIRO', 'Parceiro'), ('NEGOCIARAM', 'Já negociaram')], max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('empresa_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relacoes_como_a', to='core.empresa')),
                ('empresa_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relacoes_como_b', to='core.empresa')),
            ],
            options={
                'unique_together': {('empresa_a', 'empresa_b')},
            },
        ),
    ]
